name: Unit Testing Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Setup deps
        uses: ./.github/actions/install-deps

      - name: Run unit Tests
        run: pnpm test:coverage --silent

      - name: "Report Coverage"
        if: ${{ always() && !github.event.pull_request.head.repo.fork }}
        uses: davelosert/vitest-coverage-report-action@v2

      - name: "Upload Coverage"
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
